apiVersion: v1
kind: Service
metadata:
  name: metrics-demo
  namespace: default
  labels:
    app: metrics-demo
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 9090
  selector:
    app: metrics-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-demo
  template:
    metadata:
      labels:
        app: metrics-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: app
        image: ghcr.io/stefanprodan/podinfo:6.5.0
        ports:
        - name: web
          containerPort: 8080
        - name: metrics
          containerPort: 9090
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
