"""add foreign keys

Revision ID: 062a37940dd0
Revises: f2dd9cccc1e4
Create Date: 2026-05-02 23:29:09.763541

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "062a37940dd0"
down_revision: Union[str, Sequence[str], None] = "f2dd9cccc1e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "metrics_snapshots", "deployments", ["deployment_id"], ["id"], ondelete="CASCADE"
    )
    op.create_index(
        op.f("ix_rollbacks_deployment_id"), "rollbacks", ["deployment_id"], unique=False
    )
    op.create_foreign_key(
        None, "rollbacks", "deployments", ["deployment_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rollbacks", type_="foreignkey")
    op.drop_index(op.f("ix_rollbacks_deployment_id"), table_name="rollbacks")
    op.drop_constraint(None, "metrics_snapshots", type_="foreignkey")
    # ### end Alembic commands ###
