"""Initial Schema

Revision ID: f2dd9cccc1e4
Revises: 
Create Date: 2026-02-18 18:10:08.932915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2dd9cccc1e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('git_branch', sa.String(length=255), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=False),
    sa.Column('deployed_by', sa.String(length=255), nullable=True),
    sa.Column('argocd_revision', sa.String(length=255), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_app_name'), 'deployments', ['app_name'], unique=False)
    op.create_index(op.f('ix_deployments_deployed_at'), 'deployments', ['deployed_at'], unique=False)
    op.create_table('git_commits',
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_approved_by', sa.String(length=255), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sha')
    )
    op.create_table('metrics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('latency_p50', sa.Float(), nullable=True),
    sa.Column('latency_p95', sa.Float(), nullable=True),
    sa.Column('latency_p99', sa.Float(), nullable=True),
    sa.Column('request_rate', sa.Float(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_snapshots_deployment_id'), 'metrics_snapshots', ['deployment_id'], unique=False)
    op.create_table('rollbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=False),
    sa.Column('rolled_back_by', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('target_commit_sha', sa.String(length=40), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rollbacks')
    op.drop_index(op.f('ix_metrics_snapshots_deployment_id'), table_name='metrics_snapshots')
    op.drop_table('metrics_snapshots')
    op.drop_table('git_commits')
    op.drop_index(op.f('ix_deployments_deployed_at'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_app_name'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
